/**
 * Session lifecycle methods for the App Builder Host BFF. Each Remote method
 * delegates to the upstream `@deepseek-ai/dsh-api-session-controller`
 * service (`ctx.sessionController`), which already enforces the workspace,
 * cwd, and preset conflicts and owns the cold-read / live-stream machinery.
 * The App Builder BFF adds the project-aware wrapper: `startSession` uses
 * the project's canonical root as the Session `cwd`, and the other four
 * methods forward to the controller unchanged.
 * @module @deepseek-ai/dsh-app-builder-api/sessions
 */

import { TypertRemoteFailure } from '@deepseek-ai/dsh-typert-protocol'
import type { Context } from '@deepseek-ai/cordis'
import type { ProjectId } from '@deepseek-ai/dsh-app-builder-project'
import type { SessionHeader } from '@deepseek-ai/dsh-session'
import type { SessionPage } from '@deepseek-ai/dsh-api-session-controller'
import type {
  ForkSessionRequest,
  ForkSessionValue,
  GetTranscriptRequest,
  GetTranscriptValue,
  ResumeSessionRequest,
  ResumeSessionValue,
  SendMessageRequest,
  SendMessageValue,
  StartSessionRequest,
  StartSessionValue,
} from './types.ts'

/**
 * Resolve `ctx.sessionController` from the host context. The controller is
 * a required peer of the App Builder BFF (every App Builder composition
 * mounts it), so an absent controller is a misconfiguration; the helper
 * throws a typed `service-unavailable` failure rather than a generic
 * TypeError.
 * @param ctx - Cordis context.
 * @returns the SessionController service.
 */
function sessionControllerOf(ctx: Context): unknown {
  const controller: unknown = ctx.get('sessionController')
  if (controller === undefined) {
    throw new TypertRemoteFailure({
      code: 'service-unavailable',
      message: 'app-builder.api session methods require @deepseek-ai/dsh-api-session-controller to be mounted',
      details: {},
    })
  }
  return controller
}

/**
 * Create or idempotently adopt one Session rooted at the project's canonical
 * path. The Session id is generated by the upstream controller when the
 * caller does not supply one.
 * @param ctx - Cordis context.
 * @param request - start payload.
 * @returns the new Session id and resolved cwd.
 */
export async function startSessionRemote(
  ctx: Context,
  request: StartSessionRequest,
): Promise<StartSessionValue> {
  const project = ctx.appBuilderProjects.get(request.projectId as ProjectId)
  if (project === undefined) {
    throw new TypertRemoteFailure({
      code: 'not-found',
      message: `startSession: no project with id ${String(request.projectId)}`,
      details: { projectId: request.projectId },
    })
  }
  const controller = sessionControllerOf(ctx) as {
    create(req: { sessionId?: string; cwd?: string; workspaceId?: string }): Promise<{ sessionId: string }>
  }
  const value = await controller.create({
    ...(request.sessionId !== undefined ? { sessionId: request.sessionId } : {}),
    cwd: project.rootPath,
  })
  return { sessionId: value.sessionId, projectId: request.projectId, cwd: project.rootPath }
}

/**
 * Admit one user-facing prompt on an attached Session. Delegates to the
 * controller's `prompt` Remote method which validates the Session is
 * attached and queues the message for the Agent.
 * @param ctx - Cordis context.
 * @param request - prompt payload.
 * @returns the admitted Session id and sequence number.
 */
export async function sendMessageRemote(
  ctx: Context,
  request: SendMessageRequest,
): Promise<SendMessageValue> {
  const controller = sessionControllerOf(ctx) as {
    prompt(req: { sessionId: string; content: string; source?: 'user' | 'api' }, signal?: AbortSignal): Promise<{ sessionId: string; seq: number }>
  }
  const value = await controller.prompt({
    sessionId: request.sessionId,
    content: request.content,
    source: request.source ?? 'api',
  })
  return { sessionId: value.sessionId, accepted: true, seq: value.seq }
}

/**
 * Read one cold-safe, message-aligned Session history page. Delegates to
 * the controller's `page` Remote method which handles persistence reads
 * with the supplied abort signal.
 * @param ctx - Cordis context.
 * @param request - page payload.
 * @param signal - caller cancellation for the persistence layer.
 * @returns the requested page.
 */
export async function getTranscriptRemote(
  ctx: Context,
  request: GetTranscriptRequest,
  signal: AbortSignal,
): Promise<GetTranscriptValue> {
  const controller = sessionControllerOf(ctx) as {
    inspect(sessionId: string, signal?: AbortSignal): Promise<{ meta: SessionHeader; events: readonly { seq: number }[] }>
    page(
      req: { sessionId: string; fromSeq?: number; maxMessages?: number },
      signal: AbortSignal,
    ): Promise<SessionPage>
  }
  const [inspection, page]: [
    { meta: SessionHeader; events: readonly { seq: number }[] },
    SessionPage,
  ] = await Promise.all([
    controller.inspect(request.sessionId),
    controller.page(
      {
        sessionId: request.sessionId,
        ...(request.fromSeq !== undefined ? { fromSeq: request.fromSeq } : {}),
        ...(request.maxMessages !== undefined ? { maxMessages: request.maxMessages } : {}),
      },
      signal,
    ),
  ])
  const cursor = inspection.events.at(-1)?.seq ?? -1
  return {
    sessionId: request.sessionId,
    header: inspection.meta,
    cursor,
    records: page.records,
    hasMore: page.hasMore,
  }
}

/**
 * Fork one cold-readable completed-turn prefix into a new Session.
 * Delegates to the controller's `fork` Remote method.
 * @param ctx - Cordis context.
 * @param request - fork payload.
 * @returns the source / new Session ids and the anchor seq.
 */
export async function forkSessionRemote(
  ctx: Context,
  request: ForkSessionRequest,
): Promise<ForkSessionValue> {
  const controller = sessionControllerOf(ctx) as {
    fork(req: { sessionId: string; anchorSeq?: number }): Promise<{ sourceSessionId: string; newSessionId: string; anchorSeq: number }>
  }
  const value = await controller.fork({
    sessionId: request.sessionId,
    ...(request.anchorSeq !== undefined ? { anchorSeq: request.anchorSeq } : {}),
  })
  return {
    sourceSessionId: value.sourceSessionId,
    newSessionId: value.newSessionId,
    anchorSeq: value.anchorSeq,
  }
}

/**
 * Cold-resume one durable Session without re-attaching its Agent. Returns
 * the Session header so the caller can decide whether to call
 * `startSession` (which attaches) or just read.
 * @param ctx - Cordis context.
 * @param request - resume payload.
 * @returns the resumed Session header.
 */
export async function resumeSessionRemote(
  ctx: Context,
  request: ResumeSessionRequest,
): Promise<ResumeSessionValue> {
  const controller = sessionControllerOf(ctx) as {
    inspect(sessionId: string, signal?: AbortSignal): Promise<{ meta: SessionHeader }>
  }
  const inspection = await controller.inspect(request.sessionId)
  return {
    sessionId: request.sessionId,
    header: inspection.meta,
    resumed: true,
  }
}
